;[
    {
        Country: 'United States of America',
        CountryCode: '',
        Province: '',
        City: '',
        CityCode: '',
        Lat: '0',
        Lon: '0',
        Cases: 1,
        Status: 'confirmed',
        Date: '2020-01-22T00:00:00Z',
    },
    {
        Country: 'United States of America',
        CountryCode: '',
        Province: '',
        City: '',
        CityCode: '',
        Lat: '0',
        Lon: '0',
        Cases: 1,
        Status: 'confirmed',
        Date: '2020-01-23T00:00:00Z',
    },
]
